{
  service: "aws",
  frameworkVersion: "3",

  useDotenv: true,

  package: {
    individually: true,
    excludeDevDependencies: true,
  },

  provider: {
    name: "aws",
    runtime: "nodejs16.x",
  },

  plugins: [
    "serverless-plugin-typescript",
    "serverless-dotenv-plugin"
  ],

  functions: {
    app: {
      name: "nestfi-ai-cm-bot",
      handler: "app.handler",
      timeout: 14,
      memorySize: 256,
      events: [
        {
          httpApi: {
            path: "/bot",
            method: "post",
          },
        },
      ],
    },
  },
}
